[package]
name = "media-backup-agent-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
media-backup-crypto = { path = "../crypto" }
media-backup-protocol = { path = "../protocol" }
sarmg-agent-fs-safety = { git = "https://github.com/isarmg/sarmg-foundation-agent.git", rev = "a5b3158aa62af8189dd909500758cee649898e5c", version = "=0.6.0" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
blake3.workspace = true
