[package]
name = "photo-backup-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
argon2 = "0.5"
axum.workspace = true
base64.workspace = true
blake3.workspace = true
bytes.workspace = true
photo-backup-protocol = { path = "../protocol" }
rand.workspace = true
sarmg-platform-postgres.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
subtle.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
